name: caik
channels:
  - conda-forge
  - pytorch
dependencies:
  - python = 3.6
  - pip
  - numpy
  - tqdm
  - pytorch
  - ffmpeg-python
  - importlib_resources
  - norbert==0.2.1
  - pandas==1.1.2
  - requests
  - setuptools>=41.0.0
  - librosa==0.8.0
  - pytest
  - pytest-xdist
  - torchvision
  - tensorflow-gpu